# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Récapitulatif des fichiers de données</div></b>

In [1]:
!ls -al /opt/spark/donnees

total 48884
drwxrwxr-x 8  1000  1000     4096 Oct  2 15:28 .
drwxr-xr-x 1 spark spark     4096 Oct  2 13:59 ..
drwxrwxr-x 2  1000  1000     4096 Oct  2 13:43 ebrasil
-rw-rw-r-- 1  1000  1000   940317 Oct  2 13:43 export_sql.parquet
drwxrwxr-x 2  1000  1000     4096 Oct  2 13:43 input
drwxrwxr-x 2  1000  1000     4096 Oct  2 13:43 logs
drwxrwxr-x 2  1000  1000     4096 Oct  2 13:43 log_web_access
drwxrwxr-x 2  1000  1000     4096 Oct  2 13:43 meteo
-rw-rw-r-- 1  1000  1000 32797342 Oct  2 13:43 meteo.gzip
drwxrwxr-x 2  1000  1000     4096 Oct  2 13:43 opendata
-rw-rw-r-- 1  1000  1000     2618 Oct  2 13:43 postesSynop.csv
-rw-rw-r-- 1  1000  1000     3449 Oct  2 15:28 README.md
-rw-rw-r-- 1  1000  1000 16266066 Oct  2 13:43 Web.Server.Access10.gzip

In [2]:
!ls -al ../donnees/ebrasil

total 110948
drwxrwxr-x 2 1000 1000     4096 Oct  2 13:43 .
drwxrwxr-x 8 1000 1000     4096 Oct  2 15:28 ..
-rw-rw-r-- 1 1000 1000  9033957 Oct  2 13:43 olist_customers_dataset.csv
-rw-rw-r-- 1 1000 1000 48714816 Oct  2 13:43 olist_geolocation_dataset.csv
-rw-rw-r-- 1 1000 1000 15438671 Oct  2 13:43 olist_order_items_dataset.csv
-rw-rw-r-- 1 1000 1000  5777138 Oct  2 13:43 olist_order_payments_dataset.csv
-rw-rw-r-- 1 1000 1000 14409007 Oct  2 13:43 olist_order_reviews_dataset.csv
-rw-rw-r-- 1 1000 1000 17654914 Oct  2 13:43 olist_orders_dataset.csv
-rw-rw-r-- 1 1000 1000  2379446 Oct  2 13:43 olist_products_dataset.csv
-rw-rw-r-- 1 1000 1000   174703 Oct  2 13:43 olist_sellers_dataset.csv
-rw-rw-r-- 1 1000 1000     2542 Oct  2 13:43 product_category_name_translation.csv

In [3]:
!ls -al ../donnees/meteo

total 143612
drwxrwxr-x 2 1000 1000    4096 Oct  2 13:43 .
drwxrwxr-x 8 1000 1000    4096 Oct  2 15:28 ..
-rw-rw-r-- 1 1000 1000 4189020 Oct  2 13:43 synop.202301.csv
-rw-rw-r-- 1 1000 1000 3626128 Oct  2 13:43 synop.202302.csv
-rw-rw-r-- 1 1000 1000 4105061 Oct  2 13:43 synop.202303.csv
-rw-rw-r-- 1 1000 1000 4041942 Oct  2 13:43 synop.202304.csv
-rw-rw-r-- 1 1000 1000 4203446 Oct  2 13:43 synop.202305.csv
-rw-rw-r-- 1 1000 1000 4083804 Oct  2 13:43 synop.202306.csv
-rw-rw-r-- 1 1000 1000 4098443 Oct  2 13:43 synop.202307.csv
-rw-rw-r-- 1 1000 1000 4215978 Oct  2 13:43 synop.202308.csv
-rw-rw-r-- 1 1000 1000 4054875 Oct  2 13:43 synop.202309.csv
-rw-rw-r-- 1 1000 1000 4107655 Oct  2 13:43 synop.202310.csv
-rw-rw-r-- 1 1000 1000 4009103 Oct  2 13:43 synop.202311.csv
-rw-rw-r-- 1 1000 1000 4186069 Oct  2 13:43 synop.202312.csv
-rw-rw-r-- 1 1000 1000 4164769 Oct  2 13:43 synop.202401.csv
-rw-rw-r-- 1 1000 1000 3865487 Oct  2 13:43 synop.202402.csv
-rw-rw-r-- 1 1000 1000 4229957 Oct  2 13:43 synop.202403.csv
-rw-rw-r-- 1 1000 1000 4096596 Oct  2 13:43 synop.202404.csv
-rw-rw-r-- 1 1000 1000 4270333 Oct  2 13:43 synop.202405.csv
-rw-rw-r-- 1 1000 1000 4090948 Oct  2 13:43 synop.202406.csv
-rw-rw-r-- 1 1000 1000 4191109 Oct  2 13:43 synop.202407.csv
-rw-rw-r-- 1 1000 1000 4201423 Oct  2 13:43 synop.202408.csv
-rw-rw-r-- 1 1000 1000 4047347 Oct  2 13:43 synop.202409.csv
-rw-rw-r-- 1 1000 1000 4125068 Oct  2 13:43 synop.202410.csv
-rw-rw-r-- 1 1000 1000 4009275 Oct  2 13:43 synop.202411.csv
-rw-rw-r-- 1 1000 1000 4168390 Oct  2 13:43 synop.202412.csv
-rw-rw-r-- 1 1000 1000 4143578 Oct  2 13:43 synop.202501.csv
-rw-rw-r-- 1 1000 1000 3684501 Oct  2 13:43 synop.202502.csv
-rw-rw-r-- 1 1000 1000 4073763 Oct  2 13:43 synop.202503.csv
-rw-rw-r-- 1 1000 1000 3915948 Oct  2 13:43 synop.202504.csv
-rw-rw-r-- 1 1000 1000 4126452 Oct  2 13:43 synop.202505.csv
-rw-rw-r-- 1 1000 1000 3932512 Oct  2 13:43 synop.202506.csv
-rw-rw-r-- 1 1000 1000 4111781 Oct  2 13:43 synop.202507.csv
-rw-rw-r-- 1 1000 1000 4082704 Oct  2 13:43 synop.202508.csv
-rw-rw-r-- 1 1000 1000 4005894 Oct  2 13:43 synop.202509.csv
-rw-rw-r-- 1 1000 1000 4214397 Oct  2 13:43 synop.202510.csv
-rw-rw-r-- 1 1000 1000 4069074 Oct  2 13:43 synop.202511.csv
-rw-rw-r-- 1 1000 1000 4238763 Oct  2 13:43 synop.202512.csv

In [4]:
!ls -al python

total 14024
drwxr-xr-x 5 spark spark    4096 Oct  2 17:00  .
drwxr-xr-x 9 spark spark    4096 Oct  3 12:49  ..
-rw-rw-r-- 1 spark spark   11508 Oct  2 16:59 '09-Création de la DataFrame - logs d’un serveur Web.ipynb'
-rw-rw-r-- 1 spark spark 9918910 Oct  2 17:00 '10-Analyse exploratoire des logs d’un serveur Web.ipynb'
-rw-rw-r-- 1 spark spark   15766 Oct  2 13:43 '11-Consolidation des donnée meteo.ipynb'
-rw-rw-r-- 1 spark spark 4389853 Oct  2 13:43 '12-Analyse  exploratoire des données meteo.ipynb'
drwxr-xr-x 4 spark spark    4096 Oct  2 15:43  Analyse.exploratoire.logs
drwxr-xr-x 2 spark spark    4096 Oct  2 15:38  .ipynb_checkpoints
drwxr-xr-x 3 spark spark    4096 Oct  2 16:57  outils

# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Base de données `formation`</div></b>

In [5]:
import sqlalchemy, pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import URL


url = URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="formation",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

with engine.connect() as connexion:
    print(connexion.execute(text("SELECT current_database(), current_user")).fetchone())

connection = engine.connect()

('formation', 'formation')

In [6]:
requete  = "select * from customers"
pd.read_sql_query(requete, connection)

,customer_id,first_name,last_name,country,segment,created_at
0,1,Alice,Martin,FR,Retail,2026-10-02 13:59:25.209205+00:00
1,2,Benoit,Durand,FR,SMB,2026-10-02 13:59:25.209205+00:00
2,3,Clara,Bernard,BE,Enterprise,2026-10-02 13:59:25.209205+00:00
3,4,David,Muller,DE,Retail,2026-10-02 13:59:25.209205+00:00
4,5,Eva,Rossi,IT,SMB,2026-10-02 13:59:25.209205+00:00

In [7]:
requete  = "select * from order_lines"
pd.read_sql_query(requete, connection)

   order_id  product_id  quantity  unit_price
0      1001         101         1      1299.0
1      1001         103         1        79.0
2      1002         102         2       349.0
3      1003         105         4       159.0
4      1004         104         3        49.0
5      1005         103         2        79.0

In [8]:
requete  = "select * from orders"
pd.read_sql_query(requete, connection)

   order_id  customer_id                         order_ts   status    source
0      1001            1 2026-09-27 13:59:25.218556+00:00     PAID  postgres
1      1002            2 2026-09-29 13:59:25.218556+00:00     PAID  postgres
2      1003            3 2026-10-01 13:59:25.218556+00:00  SHIPPED  postgres
3      1004            1 2026-10-02 07:59:25.218556+00:00     PAID  postgres
4      1005            5 2026-10-02 12:59:25.218556+00:00      NEW  postgres

In [9]:
requete  = "select * from products"
pd.read_sql_query(requete, connection)

   product_id product_name     category  unit_price
0         101   Laptop Pro    Computers      1299.0
1         102   Monitor 27     Displays       349.0
2         103     Keyboard  Accessories        79.0
3         104        Mouse  Accessories        49.0
4         105   Dock USB-C  Accessories       159.0

# <b><div style='padding:15px;background-color:#d8dcd6;color:#030aa7;font-size:120%;text-align: left'>Base de données `ebrasil`</div></b>

In [10]:
url = URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="ebrasil",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

connection = engine.connect()

<img src="https://raw.githubusercontent.com/rbizoi/FormationBigDataBI/refs/heads/master/images/ebrasil.png" width="850">

In [11]:
# requete  = """
#             select 'orders     ' table, count(*) enregistrements      from orders       
#             union all
#             select 'customers  ' , count(*) from customers    
#             union all
#             select 'sellers    ' , count(*) from sellers      
#             union all
#             select 'items      ' , count(*) from items        
#             union all
#             select 'payments   ' , count(*) from payments     
#             union all
#             select 'reviews    ' , count(*) from reviews      
#             union all
#             select 'reviews_p  ' , count(*) from reviews_p    
#             union all
#             select 'products   ' , count(*) from products     
#             union all
#             select 'geolocation' , count(*) from geolocation"""
# pd.read_sql_query(requete, connection)